import { expect, it } from "vitest"
import * as THREE from "three"
import { StaticInstanceBatch, staticInstanceKey } from "./static-instances"

it("combines scenery transforms and colors, uploads only changed views, and keeps source geometry", () => {
  const geometry = new THREE.BoxGeometry(), material = new THREE.MeshLambertMaterial()
  const a = new THREE.InstancedMesh(geometry, material, 1), b = new THREE.InstancedMesh(geometry, material, 2)
  a.setMatrixAt(0, new THREE.Matrix4().makeTranslation(1, 2, 3))
  b.setMatrixAt(0, new THREE.Matrix4().makeTranslation(4, 5, 6))
  b.setMatrixAt(1, new THREE.Matrix4().makeTranslation(7, 8, 9))
  a.setColorAt(0, new THREE.Color("red")); b.setColorAt(0, new THREE.Color("green")); b.setColorAt(1, new THREE.Color("blue"))
  b.position.x = 10; b.updateMatrixWorld()
  const batch = new StaticInstanceBatch(), matrix = new THREE.Matrix4(), color = new THREE.Color()
  batch.write([a, b])
  expect(batch.mesh!.count).toBe(3)
  expect(batch.mesh!.geometry.getAttribute("position").array).toEqual(geometry.getAttribute("position").array)
  batch.mesh!.getMatrixAt(2, matrix)
  expect(matrix.elements.slice(12, 15)).toEqual([17, 8, 9])
  batch.mesh!.getColorAt(2, color)
  expect(color.getHex()).toBe(0x0000ff)
  const matrices = batch.mesh!.instanceMatrix
  const version = matrices.version
  batch.write([a, b])
  expect(matrices.version).toBe(version)
  b.setMatrixAt(1, new THREE.Matrix4().makeTranslation(0, 0, 0)); b.instanceMatrix.needsUpdate = true
  batch.write([a, b]); batch.mesh!.getMatrixAt(2, matrix)
  expect(matrix.elements.slice(12, 15)).toEqual([10, 0, 0])
  batch.write([b]); expect(batch.mesh!.count).toBe(2)
  batch.write([]); expect(batch.root.visible).toBe(false)
  batch.write([a]); expect(batch.root.visible).toBe(true)
  expect(batch.mesh!.count).toBe(1)
  expect(staticInstanceKey(a)).toBe(staticInstanceKey(b))
  b.layers.set(1); expect(staticInstanceKey(a)).not.toBe(staticInstanceKey(b))
  const camera = new THREE.OrthographicCamera(-3, 3, 4, -4, .1, 100)
  camera.position.set(0, 0, 20); camera.updateMatrixWorld()
  const frustum = new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse))
  batch.write([a, b], frustum, 1)
  expect(batch.mesh!.count).toBe(1)
  camera.position.x = 10; camera.updateMatrixWorld()
  frustum.setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse))
  batch.write([a, b], frustum, 2)
  expect(batch.mesh!.count).toBe(1)
  batch.mesh!.getMatrixAt(0, matrix)
  expect(matrix.elements.slice(12, 15)).toEqual([10, 0, 0])
  batch.write([a, b], undefined, 3, 2)
  expect(batch.mesh!.count).toBe(0)
  batch.write([a, b], undefined, 3, 0)
  expect(batch.mesh!.count).toBe(3)
  batch.dispose(); a.dispose(); b.dispose(); geometry.dispose(); material.dispose()
})
