// Generated by node scripts/icon-inventory.mjs from application imports and public/game-icons.
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Crosshair, GripVertical, Info, Loader2, LocateFixed, MapPlus, Menu, Minus, Moon, MoreHorizontal, PanelLeft, PanelRight, Pause, Play, RefreshCw, RotateCcw, RotateCw, Search, Settings, Shuffle, Square, StepForward, Sun, Users, Volume2, VolumeX, X } from "lucide-react"

export const UI_ICONS = [
  { ...{"id":"ui-ArrowLeft","label":"Arrow Left","sources":["components/asset-editor-frame.tsx","components/ui/carousel.tsx"]}, component: ArrowLeft },
  { ...{"id":"ui-ArrowRight","label":"Arrow Right","sources":["components/ui/carousel.tsx"]}, component: ArrowRight },
  { ...{"id":"ui-ArrowUpRight","label":"Arrow Up Right","sources":["components/asset-editor-frame.tsx","components/base-person-lab.tsx"]}, component: ArrowUpRight },
  { ...{"id":"ui-Check","label":"Check","sources":["components/base-person-lab.tsx","components/ui/checkbox.tsx","components/ui/chrome-controls.tsx","components/ui/context-menu.tsx","components/ui/dropdown-menu.tsx","components/ui/menubar.tsx","components/ui/select.tsx"]}, component: Check },
  { ...{"id":"ui-ChevronDown","label":"Chevron Down","sources":["components/ui/accordion.tsx","components/ui/calendar.tsx","components/ui/chrome-controls.tsx","components/ui/navigation-menu.tsx","components/ui/select.tsx"]}, component: ChevronDown },
  { ...{"id":"ui-ChevronLeft","label":"Chevron Left","sources":["components/ui/calendar.tsx","components/ui/pagination.tsx"]}, component: ChevronLeft },
  { ...{"id":"ui-ChevronRight","label":"Chevron Right","sources":["components/asset-editor-frame.tsx","components/game/game-hud.tsx","components/ui/breadcrumb.tsx","components/ui/calendar.tsx","components/ui/context-menu.tsx","components/ui/dropdown-menu.tsx","components/ui/menubar.tsx","components/ui/pagination.tsx"]}, component: ChevronRight },
  { ...{"id":"ui-ChevronUp","label":"Chevron Up","sources":["components/ui/select.tsx"]}, component: ChevronUp },
  { ...{"id":"ui-Circle","label":"Circle","sources":["components/ui/context-menu.tsx","components/ui/dropdown-menu.tsx","components/ui/menubar.tsx","components/ui/radio-group.tsx"]}, component: Circle },
  { ...{"id":"ui-Crosshair","label":"Crosshair","sources":["components/game/follow-button.tsx"]}, component: Crosshair },
  { ...{"id":"ui-GripVertical","label":"Grip Vertical","sources":["components/ui/resizable.tsx"]}, component: GripVertical },
  { ...{"id":"ui-Info","label":"Info","sources":["components/asset-editor-frame.tsx"]}, component: Info },
  { ...{"id":"ui-Loader2","label":"Loader2","sources":["components/ui/spinner.tsx"]}, component: Loader2 },
  { ...{"id":"ui-LocateFixed","label":"Locate Fixed","sources":["components/game/follow-button.tsx"]}, component: LocateFixed },
  { ...{"id":"ui-MapPlus","label":"Map Plus","sources":["components/game/new-map-dialog.tsx"]}, component: MapPlus },
  { ...{"id":"ui-Menu","label":"Menu","sources":["components/game/game-hud.tsx"]}, component: Menu },
  { ...{"id":"ui-Minus","label":"Minus","sources":["components/ui/input-otp.tsx"]}, component: Minus },
  { ...{"id":"ui-Moon","label":"Moon","sources":["components/chrome-provider.tsx"]}, component: Moon },
  { ...{"id":"ui-MoreHorizontal","label":"More Horizontal","sources":["components/ui/breadcrumb.tsx","components/ui/pagination.tsx"]}, component: MoreHorizontal },
  { ...{"id":"ui-PanelLeft","label":"Panel Left","sources":["components/asset-editor-frame.tsx","components/ui/sidebar.tsx"]}, component: PanelLeft },
  { ...{"id":"ui-PanelRight","label":"Panel Right","sources":["components/asset-editor-frame.tsx"]}, component: PanelRight },
  { ...{"id":"ui-Pause","label":"Pause","sources":["components/animal-lab.tsx","components/base-person-lab.tsx","components/game/hud-controls.tsx","components/lab-controls.tsx","components/tree-lab/ent-lab.tsx"]}, component: Pause },
  { ...{"id":"ui-Play","label":"Play","sources":["components/animal-lab.tsx","components/base-person-lab.tsx","components/game/hud-controls.tsx","components/lab-controls.tsx","components/tree-lab/ent-lab.tsx"]}, component: Play },
  { ...{"id":"ui-RefreshCw","label":"Refresh Cw","sources":["components/game/seed-field.tsx"]}, component: RefreshCw },
  { ...{"id":"ui-RotateCcw","label":"Rotate Ccw","sources":["components/animal-lab.tsx","components/base-person-lab.tsx","components/building-lab/procedural-workshop.tsx","components/game/hud-controls.tsx","components/lab-controls.tsx"]}, component: RotateCcw },
  { ...{"id":"ui-RotateCw","label":"Rotate Cw","sources":["components/game/hud-controls.tsx"]}, component: RotateCw },
  { ...{"id":"ui-Search","label":"Search","sources":["components/ui/command.tsx","components/workspace-navigation.tsx"]}, component: Search },
  { ...{"id":"ui-Settings","label":"Settings","sources":["components/game/game-hud.tsx"]}, component: Settings },
  { ...{"id":"ui-Shuffle","label":"Shuffle","sources":["components/asset-editor-frame.tsx"]}, component: Shuffle },
  { ...{"id":"ui-Square","label":"Square","sources":["components/character-sound-controls.tsx"]}, component: Square },
  { ...{"id":"ui-StepForward","label":"Step Forward","sources":["components/lab-controls.tsx"]}, component: StepForward },
  { ...{"id":"ui-Sun","label":"Sun","sources":["components/chrome-provider.tsx"]}, component: Sun },
  { ...{"id":"ui-Users","label":"Users","sources":["components/game/game-hud.tsx"]}, component: Users },
  { ...{"id":"ui-Volume2","label":"Volume2","sources":["components/character-sound-controls.tsx","components/game/music-player.tsx"]}, component: Volume2 },
  { ...{"id":"ui-VolumeX","label":"Volume X","sources":["components/character-sound-controls.tsx","components/game/music-player.tsx"]}, component: VolumeX },
  { ...{"id":"ui-X","label":"X","sources":["components/asset-editor-frame.tsx","components/game/game-hud.tsx","components/ui/dialog.tsx","components/ui/sheet.tsx","components/ui/toast.tsx"]}, component: X },
]

export const SVG_ICONS = [
  {
    "id": "svg-camp",
    "label": "Camp",
    "url": "/game-icons/camp.svg",
    "sources": [
      "public/game-icons/camp.svg"
    ]
  },
  {
    "id": "svg-cross",
    "label": "Cross",
    "url": "/game-icons/cross.svg",
    "sources": [
      "public/game-icons/cross.svg"
    ]
  },
  {
    "id": "svg-garden",
    "label": "Garden",
    "url": "/game-icons/garden.svg",
    "sources": [
      "public/game-icons/garden.svg"
    ]
  },
  {
    "id": "svg-inn",
    "label": "Inn",
    "url": "/game-icons/inn.svg",
    "sources": [
      "public/game-icons/inn.svg"
    ]
  },
  {
    "id": "svg-road",
    "label": "Road",
    "url": "/game-icons/road.svg",
    "sources": [
      "public/game-icons/road.svg"
    ]
  },
  {
    "id": "svg-tavern",
    "label": "Tavern",
    "url": "/game-icons/tavern.svg",
    "sources": [
      "public/game-icons/tavern.svg"
    ]
  },
  {
    "id": "svg-timber",
    "label": "Timber",
    "url": "/game-icons/timber.svg",
    "sources": [
      "public/game-icons/timber.svg"
    ]
  },
  {
    "id": "svg-app",
    "label": "App icon",
    "url": "/icon.svg",
    "sources": [
      "app/layout.tsx",
      "public/icon.svg"
    ]
  },
  {
    "id": "app-favicon.ico",
    "label": "Browser favicon",
    "url": "/favicon.ico",
    "sources": [
      "public/favicon.ico"
    ]
  },
  {
    "id": "app-apple-icon.png",
    "label": "Apple app icon",
    "url": "/apple-icon.png",
    "sources": [
      "public/apple-icon.png"
    ]
  },
  {
    "id": "app-icon-192.png",
    "label": "App icon · 192",
    "url": "/icon-192.png",
    "sources": [
      "public/icon-192.png"
    ]
  },
  {
    "id": "app-icon-512.png",
    "label": "App icon · 512",
    "url": "/icon-512.png",
    "sources": [
      "public/icon-512.png"
    ]
  },
  {
    "id": "app-icon-maskable-512.png",
    "label": "Maskable app icon",
    "url": "/icon-maskable-512.png",
    "sources": [
      "public/icon-maskable-512.png"
    ]
  }
]
