"use client"

import { useLayoutEffect, useMemo, useRef } from "react"
import { useLoader } from "@react-three/fiber"
import * as THREE from "three"

import { deriveSeed, makeRng, SEED_STREAM } from "@/lib/game/rng"
import { TERRAIN } from "@/lib/game/map/terrain"
import { tileToWorldX, tileToWorldZ, type GameMap } from "@/lib/game/map/types"
import { OUTLINE_ID_LAYER_MASK } from "@/lib/game/render/outline"

/** Top of the base slab. Must sit below the shortest terrain height. */
export const SLAB_TOP = 0.08

/** The slab is the block of earth the map sits on; its sides are the cliff. */
const SLAB_THICKNESS = 3.2
/**
 * The slab pokes out slightly past the tiles on every side. This is what kills
 * the z-fighting shimmer along the map edge — tile sides would otherwise be
 * exactly coplanar with the slab's sides — and it reads as a lip of dirt that
 * the turf sits on.
 */
const SLAB_EXPAND = 0.1
/** Generated by scripts/generate-dirt-texture.mjs. */
const DIRT_TEXTURE_URL = "/textures/dirt-side.png"

/**
 * Tiles are a hair under 1 unit so neighbouring boxes of different heights
 * never share a face plane (coplanar faces shimmer). The 0.002 seam is well
 * under a pixel at every zoom, and the grid line sits on top of it anyway.
 */
const TILE_EPS = 0.998

/**
 * Grid lines are drawn in the tile shader, not as gaps between tiles. Each tile
 * darkens a band this wide (in world units) along the edges of its top face;
 * two adjacent tiles together produce one line centred on the shared boundary.
 */
const GRID_HALF_WIDTH = 0.025
/** How much a grid line darkens the tile colour underneath it. */
const GRID_DARKEN = 0.8


/**
 * A Lambert material with the grid overlay injected. The unit box's UVs span
 * 0–1 per face and instances never rotate, so `uv` measures across the tile and
 * `normal.y` picks out the top face. fwidth-based smoothing keeps the lines
 * from shimmering at far zooms.
 */
function makeGridMaterial(): THREE.MeshLambertMaterial {
  const material = new THREE.MeshLambertMaterial()
  material.onBeforeCompile = (shader) => {
    shader.vertexShader = shader.vertexShader
      .replace(
        "#include <common>",
        "varying vec2 vGridUv;\nvarying float vGridTop;\n#include <common>",
      )
      .replace(
        "#include <uv_vertex>",
        "#include <uv_vertex>\nvGridUv = uv;\nvGridTop = step(0.5, normal.y);",
      )
    shader.fragmentShader = shader.fragmentShader
      .replace(
        "#include <common>",
        "varying vec2 vGridUv;\nvarying float vGridTop;\n#include <common>",
      )
      .replace(
        "#include <color_fragment>",
        `#include <color_fragment>
        {
          float gridDist = min(
            min(vGridUv.x, 1.0 - vGridUv.x),
            min(vGridUv.y, 1.0 - vGridUv.y)
          );
          float aa = fwidth(gridDist);
          float line = (1.0 - smoothstep(${GRID_HALF_WIDTH} - aa, ${GRID_HALF_WIDTH} + aa, gridDist)) * vGridTop;
          diffuseColor.rgb *= mix(1.0, ${GRID_DARKEN}, line);
        }`,
      )
  }
  return material
}

export function TerrainTiles({ map }: { map: GameMap }) {
  const meshRef = useRef<THREE.InstancedMesh>(null)
  const idMeshRef = useRef<THREE.InstancedMesh>(null)
  const count = map.width * map.depth

  const gridMaterial = useMemo(makeGridMaterial, [])

  useLayoutEffect(() => {
    const mesh = meshRef.current
    const idMesh = idMeshRef.current
    if (!mesh || !idMesh) return

    const matrix = new THREE.Matrix4()
    const position = new THREE.Vector3()
    const quaternion = new THREE.Quaternion()
    const scale = new THREE.Vector3()
    const color = new THREE.Color()
    // Colour grain is a function of the map's own seed, one stream per consumer.
    const rng = makeRng(deriveSeed(map.seed ?? 0, SEED_STREAM.tileJitter))

    for (let z = 0; z < map.depth; z++) {
      for (let x = 0; x < map.width; x++) {
        const index = z * map.width + x
        const def = TERRAIN[map.tiles[index]]

        // Box base sits at y=0 and the top at the terrain height, so tiles sink
        // into the slab and never show a gap from a low camera angle. Full-size
        // footprints — the grid comes from the shader overlay, not from gaps.
        position.set(tileToWorldX(map, x), def.height / 2, tileToWorldZ(map, z))
        scale.set(TILE_EPS, def.height, TILE_EPS)
        matrix.compose(position, quaternion, scale)
        mesh.setMatrixAt(index, matrix)
        idMesh.setMatrixAt(index, matrix)

        color.set(def.color)
        color.multiplyScalar(1 + (rng() - 0.5) * def.jitter)
        mesh.setColorAt(index, color)
      }
    }

    mesh.instanceMatrix.needsUpdate = true
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true
    idMesh.instanceMatrix.needsUpdate = true
  }, [map])

  const dirt = useLoader(THREE.TextureLoader, DIRT_TEXTURE_URL)
  useMemo(() => {
    dirt.colorSpace = THREE.SRGBColorSpace
    // Repeat around the cliff, but run the topsoil-to-subsoil ramp just once
    // top to bottom, so wrap horizontally and clamp vertically.
    dirt.wrapS = THREE.RepeatWrapping
    dirt.wrapT = THREE.ClampToEdgeWrapping
    dirt.repeat.set(map.width / 4, 1)
    dirt.anisotropy = 4
  }, [dirt, map])

  const slabPosition = useMemo<[number, number, number]>(
    () => [0, SLAB_TOP - SLAB_THICKNESS / 2, 0],
    [],
  )
  const slabArgs = useMemo<[number, number, number]>(
    () => [map.width + SLAB_EXPAND, SLAB_THICKNESS, map.depth + SLAB_EXPAND],
    [map],
  )

  return (
    <group>
      <mesh position={slabPosition}>
        <boxGeometry args={slabArgs} />
        <meshLambertMaterial map={dirt} />
      </mesh>

      <instancedMesh
        ref={meshRef}
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, count]}
      >
        <boxGeometry args={[1, 1, 1]} />
        <primitive object={gridMaterial} attach="material" />
      </instancedMesh>

      {/*
        Terrain in the outline pass: ID 0 (black), depth only. It takes no
        outline itself, but its depth stops hidden object seams — say two
        buildings overlapping *behind* a hill — from drawing lines through it.
      */}
      <mesh position={slabPosition} layers-mask={OUTLINE_ID_LAYER_MASK}>
        <boxGeometry args={slabArgs} />
        <meshBasicMaterial color="black" toneMapped={false} />
      </mesh>
      <instancedMesh
        ref={idMeshRef}
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, count]}
        layers-mask={OUTLINE_ID_LAYER_MASK}
      >
        <boxGeometry args={[1, 1, 1]} />
        <meshBasicMaterial color="black" toneMapped={false} />
      </instancedMesh>
    </group>
  )
}
