"use client"

import { benchmarkWork } from "@/lib/game/benchmark-work"
import { TerrainMapContext } from "./terrain-map-context"
import { createContext, useContext, memo, useEffect, useLayoutEffect, useMemo, useRef } from "react"
import { useFrame, useThree } from "@react-three/fiber"
import * as THREE from "three"

import { waterfallTurbulence } from "@/lib/game/map/waterfall-turbulence"
import { DEFAULT_ELEVATION } from "@/lib/game/map/elevation"
import { RoadSegmentTexture } from "@/lib/game/render/road-segment-texture"
import { sceneryDetail } from "@/lib/game/render/scenery-detail"
import { elevationShader } from "@/lib/game/render/terrain-elevation"
import { terrainHiddenFaces, compactTerrainFaces } from "@/lib/game/render/terrain-hidden-faces"
import { TERRAIN_BLOCK, terrainBlockState, type TerrainBlockState, terrainBlocks, sameRoadSnapshot, type TerrainBlockBounds } from "@/lib/game/render/terrain-blocks"
import { CHARACTER_PIXEL_SIZE } from "@/lib/game/render/pixel-scale"
import { terrainCorner, type CliffCorner } from "@/lib/game/map/cliff-corners"
import { waterDepthCorners } from "@/lib/game/map/water-depth-corners"
import { groundCornerTiles, groundPaintCode } from "@/lib/game/map/ground-transitions"
import { OPEN_MEADOW_TINT } from "@/lib/game/render/ground-palette"
import { TERRAIN_EDGE_GLSL, TERRAIN_EDGE_GRAIN_URL } from "@/lib/game/render/terrain-edge-grain"
import { TERRAIN_WATER_GLSL } from "@/lib/game/render/terrain-water"
import { GROUND_TRANSITIONS_GLSL } from "@/lib/game/render/ground-transitions"
import { groundGrowthField } from "@/lib/game/environment/ground-growth"
import { foundingRoadStrength, foundingRoadTraffic } from "@/lib/game/footpaths"
import { dirtFloorMask, DIRT_FLOOR_GLSL } from "@/lib/game/building-art/dirt-floor"
import { GROUND_SURFACE_GLSL, ROAD_UV_SCALE, GRASS_TEXTURE_URL } from "@/lib/game/render/ground-surface"
import { ElevationEdges } from "./elevation-edges"
import { WaterMotion } from "./water-motion"
import { StaticBlock } from "./static-block"
import { deriveSeed, makeRng, SEED_STREAM } from "@/lib/game/rng"
import { SHORE_CORNERS, shorelineCorners } from "@/lib/game/map/shoreline"
import { SHORELINE_SHAPE_GLSL } from "@/lib/game/render/shoreline-shape"
import { bridgeLayout } from "@/lib/game/map/bridges"
import { treeGroundField, TREE_GROUND_GLSL, TREE_GROUND_ATLAS } from "@/lib/game/trees/ground"
import type { TreePlacement } from "@/lib/game/trees/placement"
import {
  clampRoadTier,
  DEFAULT_ROAD_LOOK,
  DEFAULT_ROAD_TIER,
  isRoadTerrain,
  junctionShoulders,
  ROAD_TIERS,
  roadContinues,
  roadEdge,
  roadTint,
  roadWear,
  type RoadLook,
} from "@/lib/game/map/road"
import {
  MAX_WATER_DEPTH,
  TERRAIN,
  TILE_HEIGHT,
  isWoods,
  WATER_DEPTH_COLORS,
  type TerrainId,
} from "@/lib/game/map/terrain"
import { tileAt, tileToWorldX, tileToWorldZ, type GameMap } from "@/lib/game/map/types"
import { OUTLINE_ID_LAYER_MASK, ROAD_EDGE_LAYER_MASK } from "@/lib/game/render/outline"
import { diagonalRoadSegments, roadSegmentWear, type RoadSegment } from "@/lib/game/render/road-segments"
import { ROAD_SHAPE_GLSL } from "@/lib/game/render/road-shape"
import { DEFAULT_TRAFFIC } from "@/lib/game/travelers"
import { useTerrainTexture } from "./use-terrain-texture"

/** Top of the base slab. Must sit below the shortest terrain height. */
export const SLAB_TOP = 0.08

/** The slab is the block of earth the map sits on; its sides are the cliff. */
const SLAB_THICKNESS = 3.2
/**
 * The slab pokes out slightly past the tiles on every side. This is what kills
 * the z-fighting shimmer along the map edge — tile sides would otherwise be
 * exactly coplanar with the slab's sides — and it reads as a lip of dirt that
 * the turf sits on.
 */
const SLAB_EXPAND = 0.1
/** Generated by scripts/generate-dirt-texture.mjs. */
const DIRT_TEXTURE_URL = "/textures/dirt-side.png"

/**
 * The optional grid is one global lattice projected onto the terrain, not a
 * border on each tile. The shader darkens a band this wide (in world units) on
 * either side of every integer world-space line on the tiles' top faces, so
 * the lines run continuously across the map and never depend on the
 * individual boxes under them.
 */
const GRID_HALF_WIDTH = 0.025
/** How much a grid line darkens the tile colour underneath it. */
const GRID_DARKEN = 0.8

/**
 * Which ground wears the grass texture, and how strongly the tile's own colour
 * is laid over the sward first. Clear land *is* the sward — its colour is the
 * texture's average, so there is nothing to lay over. Forest starts with that
 * same open turf; prebuilt canopy-depth tiles add crisp shade and dirt.
 * Clearings retain their own tint. Bare earth, hills and the beach
 * carry sparse mineral sprites over their own colours; the road and the track
 * to the relic wear the road surface instead (see isRoadTerrain).
 */
const SWARD_OVERLAY: Partial<Record<TerrainId, number>> = {
  grass: 0,
  clearing: 0.5,
  forest: 0,
  darkwood: 0,
}

/** What the road's (rarely visible) sides wear instead of the top texture. */
const ROAD_SIDE_COLOR = "vec3(0.62, 0.51, 0.37)"

/**
 * How far the bare surface's edge wavers either side of where traffic puts it
 * (see roadWear), in tile units, before the tier's edgeWear scales it. The
 * waver is noise over *world* position, so a road tile and the land tile
 * beside it always agree at their shared boundary and the ragged line runs
 * continuously along the road.
 */
const EDGE_WAVER = 0.3

/** What a road's surface looks like at one tier, for the road material. */
interface RoadSurface {
  texture: THREE.Texture
  edgeWear: number
  segments: { texture: { value: THREE.DataTexture | null }; size: { value: THREE.Vector2 } }
  floors: THREE.DataTexture
  trail: THREE.Texture
  isDirt: boolean
  /** Live uniforms for the tunable look; the values change without a recompile. */
  look: RoadLookUniforms
}

/** The look's uniforms, plus the device pixel ratio the edge line is sized by. */
type RoadLookUniforms = Record<keyof RoadLook | "pixelRatio", { value: number }>

interface TileMaterialOptions {
  tileCoverage?: THREE.DataTexture
  grassTexture: THREE.Texture
  groundTexture: THREE.Texture
  sandTexture: THREE.Texture
  palette: THREE.DataTexture
  waterPalette: THREE.DataTexture
  growth: { texture: THREE.DataTexture; origin: THREE.Vector2 }
  treeGround: { texture: THREE.DataTexture; atlas: THREE.Texture; floor: THREE.Texture; grain: THREE.Texture; size: THREE.Vector2 }
  cliffTexture: THREE.Texture
  /**
   * Lattice origin for the optional grid overlay. Tile boundaries sit at
   * `k - width/2` in world units, so this shifts the lattice to land on them
   * for any map size. Omit for no grid.
   */
  gridOrigin?: { x: number; z: number }
  road?: RoadSurface
  /**
   * Draw nothing but the road's edge line, as coverage in the red channel.
   * The outline pass renders this over the terrain's own depth, then traces
   * the line back faintly wherever a tree stands in front of it.
   */
  edgeOnly?: boolean
}

/**
 * A Lambert material for the ground boxes, with the surfaces painted in the
 * shader from world-space XZ so nothing repeats per tile: `normal.y` picks out
 * the top face, and fwidth-based smoothing keeps every edge from shimmering at
 * far zooms.
 *
 * Every tile carries a per-instance `aSurface.x` weight and an `aOverlay` colour.
 * On plain ground `aSurface.x` flags sward tiles, whose tops wear the grass
 * texture (the instance colour is white there, so the texture carries the
 * colour) with `aOverlay` laid over it — the tile's own colour and the
 * meadow tint, folded into one tint and opacity. Both textures go
 * through `sampleTiled` on the same pixel grid as character artwork.
 *
 * With `road` set, the tile is first painted as the land it sits in, exactly
 * as the ground mesh would have painted it: the grass texture under
 * `aLandOverlay` with the grain in `aLand`. The road surface is
 * then laid over that — the tier texture by its alpha, the shade ramp on it
 * through `aOverlay`, the instance colour (the weathering tint, see
 * roadTint, and the grain) multiplied in. Only the road proper takes that
 * tint; nothing green is ever painted, so the grass on and beside a road
 * tile is one continuous surface.
 *
 * `aRoadOpen` identifies open sides (1), ordinary entrances (0), and diagonal
 * entrances (-1). Their ruts merge at junctions, while `aRoadCorners` fills broad road
 * patches. `aRoadShoulders` rounds inside junction corners across adjoining
 * grass tiles; `aSurface.zw` selects shared diagonal centrelines, including
 * their overflow. `aSurface.x` marks land-only instances and packs shoreline flags
 * above its low bit to stay within the vertex attribute budget.
 * The outer and inner edges in `aLand` (see roadWear), plus a
 * world-space waver, leave grassy verges and a median that wears with traffic.
 * Paved tiers fill the same constant-width footprint. The `look` uniforms tune the
 * surface and an outline along the combined outer edge.
 *
 * Ground tiles carry `aShoreCorners` and `aShorePaint` for triangular banks
 * and shallows. With `gridOrigin` set, the global grid lattice is drawn on top.
 */


function makeTileMaterial({
  tileCoverage,
  grassTexture,
  groundTexture,
  sandTexture,
  palette,
  waterPalette,
  growth,
  treeGround,
  cliffTexture,
  gridOrigin,
  road,
  edgeOnly = false,
}: TileMaterialOptions): THREE.MeshLambertMaterial {
  const material = new THREE.MeshLambertMaterial({ transparent: !!tileCoverage })
  material.onBeforeCompile = (shader) => {
    elevationShader(shader, !road)
    if (tileCoverage) tileCoverageShader(shader, tileCoverage)
    shader.uniforms.forestFloorMap = { value: treeGround.floor }
    shader.uniforms.terrainEdgeGrain = { value: treeGround.grain }
    shader.uniforms.treeGroundMap = { value: treeGround.texture }
    shader.uniforms.treeGroundAtlas = { value: treeGround.atlas }
    shader.uniforms.treeGroundMapSize = { value: treeGround.size }
    shader.uniforms.cliffMap = { value: cliffTexture }
    shader.uniforms.grassMap = { value: grassTexture }
    shader.uniforms.swardField = { value: growth.texture }
    shader.uniforms.swardFieldSize = { value: new THREE.Vector2(growth.texture.image.width, growth.texture.image.height) }
    shader.uniforms.swardFieldOrigin = { value: growth.origin }
    shader.uniforms.groundMap = { value: groundTexture }
    shader.uniforms.sandMap = { value: sandTexture }
    shader.uniforms.waterPalette = { value: waterPalette }
    shader.uniforms.groundPalette = { value: palette }
    shader.uniforms.groundPaletteSize = { value: new THREE.Vector2(palette.image.width, palette.image.height) }
    shader.uniforms.grassFlat = { value: new THREE.Color(TERRAIN.grass.color) }
    if (road) {
      shader.uniforms.roadMap = { value: road.texture }
      shader.uniforms.trailMap = { value: road.trail }
      shader.uniforms.roadIsDirt = { value: road.isDirt }
      shader.uniforms.dirtFloorMap = { value: road.floors }
      shader.uniforms.dirtFloorMapSize = { value: new THREE.Vector2(road.floors.image.width, road.floors.image.height) }
      shader.uniforms.waterShallow = { value: new THREE.Color(WATER_DEPTH_COLORS[0]) }
      shader.uniforms.roadSegments = road.segments.texture
      shader.uniforms.roadSegmentTextureSize = road.segments.size
      shader.uniforms.roadEdgeWear = { value: road.edgeWear }
      // Shared objects, so the look can be tuned live without a recompile.
      shader.uniforms.roadOpacity = road.look.opacity
      shader.uniforms.roadShade = road.look.shade
      shader.uniforms.roadEdgeLine = road.look.edgeLine
      shader.uniforms.roadEdgeWidth = road.look.edgeWidth
      shader.uniforms.roadPixelRatio = road.look.pixelRatio
    }
    shader.vertexShader = shader.vertexShader
      .replace(
        "#include <common>",
        `varying vec2 vWorld;
        varying vec2 vCliffUv;
        varying float vWater;
        varying float vGridTop;
        attribute vec4 aOverlay;
        varying float vGrass;
        varying vec4 vOverlay;
        varying vec2 vTileLocal;
        #ifndef USE_ROAD_MAP
          attribute vec4 aShoreCorners;
          attribute vec4 aShorePaint;
          varying vec4 vShoreCorners;
          varying vec4 vShorePaint;
          varying float vGroundDonor;
        #endif
        #ifdef USE_ROAD_MAP
          attribute vec4 aRoadOpen;
          attribute vec4 aRoadCorners;
          attribute vec4 aRoadShoulders;
          attribute vec4 aLandOverlay;
          attribute vec4 aLand;
          varying vec2 vRoadSegments;
          varying vec4 vRoadOpen;
          varying vec4 vRoadCorners;
          varying vec4 vRoadShoulders;
          varying vec4 vLandOverlay;
          varying vec4 vLand;
        #endif
        #include <common>`,
      )
      .replace(
        "#include <project_vertex>",
        `#include <project_vertex>
        {
          vec4 worldPos = vec4(transformed, 1.0);
          #ifdef USE_INSTANCING
            worldPos = instanceMatrix * worldPos;
          #endif
          worldPos = modelMatrix * worldPos;
          vWorld = worldPos.xz;
          vWater = mod(aSurface.y, 2.0);
          vCliffUv = vec2((abs(normal.x) > 0.5 ? worldPos.z : worldPos.x) / 4.0,
            1.0 - (terrainTop - worldPos.y) / ${SLAB_THICKNESS});
          vGridTop = step(0.5, normal.y);
          vGrass = aSurface.x;
          vOverlay = aOverlay;
          vTileLocal = worldPos.xz - instanceMatrix[3].xz + 0.5;
          #ifndef USE_ROAD_MAP
            vShoreCorners = aShoreCorners;
            vShorePaint = aShorePaint;
            vGroundDonor = aSurface.z;
          #endif
          #ifdef USE_ROAD_MAP
            vRoadSegments = aSurface.zw;
            vRoadOpen = aRoadOpen;
            vRoadCorners = aRoadCorners;
            vRoadShoulders = aRoadShoulders;
            vLandOverlay = aLandOverlay;
            vLand = aLand;
            // Tile-local XZ in world axes, matching the road edge flags.
            #ifdef USE_INSTANCING
              vTileLocal = (instanceMatrix * vec4(position.x, 0.0, position.z, 0.0)).xz + 0.5;
            #else
              vTileLocal = position.xz + 0.5;
            #endif
          #endif
        }`,
      )
    shader.fragmentShader = shader.fragmentShader
      .replace(
        "#include <common>",
        `varying vec2 vWorld;
        varying vec2 vCliffUv;
        varying float vWater;
        varying float vGridTop;
        varying float vGrass;
        varying vec4 vOverlay;
        varying vec2 vTileLocal;
        #ifndef USE_ROAD_MAP
          varying vec4 vShoreCorners;
          varying vec4 vShorePaint;
          varying float vGroundDonor;
        #endif
        ${SHORELINE_SHAPE_GLSL}
        uniform sampler2D cliffMap;
        uniform sampler2D grassMap;
        uniform sampler2D groundMap;
        uniform vec3 grassFlat;
        #ifdef USE_ROAD_MAP
          uniform sampler2D roadMap;
          uniform sampler2D trailMap;
          uniform sampler2D dirtFloorMap;
          uniform vec2 dirtFloorMapSize;
          uniform bool roadIsDirt;
          uniform vec3 waterShallow;
          uniform float roadEdgeWear;
          uniform float roadOpacity;
          uniform float roadShade;
          uniform float roadEdgeLine;
          uniform float roadEdgeWidth;
          uniform float roadPixelRatio;
          varying vec2 vRoadSegments;
          varying vec4 vRoadOpen;
          varying vec4 vRoadCorners;
          varying vec4 vRoadShoulders;
          varying vec4 vLandOverlay;
          varying vec4 vLand;
          ${ROAD_SHAPE_GLSL}
        #endif
        ${GROUND_SURFACE_GLSL}
        ${TERRAIN_EDGE_GLSL}
        ${TERRAIN_WATER_GLSL}
        uniform sampler2D forestFloorMap;
        ${TREE_GROUND_GLSL}
        ${GROUND_TRANSITIONS_GLSL}
        #ifdef USE_ROAD_MAP
          ${DIRT_FLOOR_GLSL}
        #endif
        #include <common>`,
      )
      .replace(
        "#include <color_fragment>",
        // The road material applies the instance colour itself, to the road
        // surface only; the ground material lets three apply it to everything.
        `${road ? "" : "#include <color_fragment>"}
        {
          vec2 world = vWorld;
          vec3 treeCover = vGridTop > 0.5 ? treeGroundCover(world) : vec3(0.0);
          vec3 grassColor = sampleSward(grassMap, world);
          // Leaf clusters, humus and moss share the native grass pixel size.
          // Broad patches reveal turf between the varied fallen-leaf motifs.
          // Two authored floor sprites share a sampler; nearest sampling keeps
          // their palette and pixel size intact, with no color gradient.
          vec2 floorPixel = floor(fract(world * ${ROAD_UV_SCALE}) * 128.0);
          vec2 floorUv = (floorPixel + vec2(treeCover.z > 0.5 ? 128.5 : 0.5, 0.5)) / vec2(256.0, 128.0);
          vec3 litter = texture2D(forestFloorMap, floorUv).rgb;
          if (treeCover.z < 0.5) litter *= vec3(1.65, 1.80, 1.55);
          float litterPatch = tileNoise(floor(world / ${CHARACTER_PIXEL_SIZE}) * ${CHARACTER_PIXEL_SIZE * .65});
          float litterCover = treeCover.z > 0.5 ? 1.0 : treeCover.y * mix(0.55, 1.0, step(0.34, litterPatch));
          grassColor = mix(grassColor, litter, litterCover);
          #ifdef USE_ROAD_MAP
            // Read the same ground palette as neighbouring terrain, then lay
            // the road's traffic-shaped ruts over it with their separate tint.
            float vEdge = vLand.y;
            float vInner = vLand.z;
            vec3 sward = groundSurface(world, grassColor);
            float shore = terrainWaterCover(world, 0.0);
            vec3 landTop = mix(sward, waterSurface(world, 0.0), shore);

            // The road proper: the tier texture, shaded, the shade ramp at
            // the road's own blend, then the weathering tint and grain.
            vec4 roadTex = sampleTiled(roadMap, world * ${ROAD_UV_SCALE}, world);
            // Empty road batches have no instance colours (all paths may
            // be covered by bridges), but their shader must still compile.
            vec3 roadColor = vec3(1.0);
            #if defined(USE_COLOR) || defined(USE_COLOR_ALPHA)
              roadColor = vColor.rgb;
            #endif
            vec3 road = roadSurfaceColor(roadTex, roadShade, vOverlay, roadColor);

            // The rut's outer edge: traffic's verge, wavering by world-space
            // noise so the edge is ragged but continuous from tile to tile;
            // the tier says how much it wavers.
            float waver = tileNoise(world * 3.7) * 0.65 + tileNoise(world * 8.3) * 0.35;
            float edge = vEdge + ${EDGE_WAVER} * roadEdgeWear * (waver - 0.5);

            // Union the individual wheel tracks, so turning traffic wears
            // through the median at a fork instead of leaving a square seam.
            // Noise over world position frays the verges continuously.
            float tuft = tileNoise(world * 7.0) * 0.6 + tileNoise(world * 15.0) * 0.4;
            vec2 shape = roadShape(vTileLocal, clamp(1.0 - vRoadOpen, 0.0, 1.0), max(-vRoadOpen, 0.0), vRoadCorners,
              edge, vInner, (tuft - 0.5) * 0.2 * roadEdgeWear);
            // Land instances carry only the adjoining shoulders and diagonals.
            if (vGrass > 0.5) shape = vec2(0.0, -1.0);
            shape = max(shape, roadShoulders(vTileLocal, vRoadShoulders,
              edge, (tuft - 0.5) * 0.2 * roadEdgeWear));
            float originalOpacity = shape.x > 0.001 ? vLand.w : 0.0;
            shape.x *= vLand.w;
            shape.y = mix(-100.0, shape.y, step(0.001, vLand.w));
            float segmentOpacity, grassWear;
            shape = max(shape, diagonalRoadShape(vTileLocal, vRoadSegments,
              edge - vEdge, edge, (tuft - 0.5) * 0.2 * roadEdgeWear, segmentOpacity, grassWear));
            segmentOpacity = max(segmentOpacity, originalOpacity);
            // First repeat visits only dull the existing grass. Keep its texture
            // and draw neither a dirt surface nor an outline until sustained use.
            landTop = mix(landTop, landTop * vec3(0.85, 0.90, 0.80), grassWear * (1.0 - shore));
            float floorBare = dirtFloorCover(world, vTileLocal);
            if (!roadIsDirt && floorBare > 0.0) {
              vec4 floorTex = sampleTiled(trailMap, world * ${ROAD_UV_SCALE}, world);
              landTop = mix(landTop, roadSurfaceColor(floorTex, roadShade, vOverlay, roadColor),
                floorBare * floorTex.a * roadOpacity * (1.0 - shore));
            }
            float bare = roadIsDirt ? max(shape.x, floorBare) : shape.x;
            float d = shape.y;
            // Turn the existing coverage ramp into crisp pixel stipple. Actual
            // traffic still controls opacity; only the spatial edge is dithered.
            float spatialBare = clamp(bare / max(segmentOpacity, 0.001), 0.0, 1.0);
            float grainBare = step(terrainGrain(world).b * 0.998 + 0.001, spatialBare) * segmentOpacity;
            if (roadIsDirt) grainBare = max(grainBare, floorBare);
            float cover = grainBare * roadTex.a * roadOpacity * (1.0 - shore);

            // A line along the edge, sized on screen like the outlines the
            // trees wear: fwidth(d) is one device pixel in tile units, so the
            // width holds at every zoom instead of scaling with the tiles.
            float px = max(fwidth(d), 0.00001);
            float halfLine = 0.5 * roadEdgeWidth * roadPixelRatio * px;
            float line = (1.0 - smoothstep(halfLine - 0.5 * px, halfLine + 0.5 * px, abs(d - edge))) * roadEdgeLine * (1.0 - shore);
            ${edgeOnly ? "diffuseColor.a = line * roadOpacity * segmentOpacity * vGridTop;" : ""}

            vec3 top = mix(landTop, road, cover) * (1.0 - 0.75 * line * roadOpacity * segmentOpacity);
            vec3 surface = mix(${ROAD_SIDE_COLOR} * roadColor, top, vGridTop);
            diffuseColor.rgb *= surface;
          #else
            // Every natural ground type shares the same adjacency-aware paint,
            // including patches that continue beneath roads and building aprons.
            if (vGridTop > 0.5) {
              vec3 land = groundSurface(world, grassColor, vGroundDonor);
              diffuseColor.rgb = mix(land, waterSurface(world, vGroundDonor), terrainWaterCover(world, vGroundDonor));
            }
          #endif
          diffuseColor.rgb *= 1.0 - treeCover.x;
          // Exposed earth uses the slab texture with the same horizontal scale
          // and a topsoil-to-subsoil ramp measured down from the local rim.
          if (vGridTop < 0.5 && vWater < 0.5) diffuseColor.rgb = texture2D(cliffMap, vCliffUv).rgb;
          #ifdef USE_GRID
            // Distance to the nearest lattice line along each axis.
            vec2 cell = fract(world + vec2(${(gridOrigin?.x ?? 0).toFixed(3)}, ${(gridOrigin?.z ?? 0).toFixed(3)}));
            vec2 axisDist = 0.5 - abs(cell - 0.5);
            float gridDist = min(axisDist.x, axisDist.y);
            float aa = fwidth(gridDist);
            float gridLine = (1.0 - smoothstep(${GRID_HALF_WIDTH} - aa, ${GRID_HALF_WIDTH} + aa, gridDist)) * vGridTop;
            diffuseColor.rgb *= mix(1.0, ${GRID_DARKEN}, gridLine);
          #endif
        }`,
      )
    // Nothing but the line: no lighting, no surface, no colour conversion —
    // just its coverage, for the outline pass to lay over the trees.
    if (edgeOnly) {
      shader.fragmentShader = shader.fragmentShader
        .replace("#include <opaque_fragment>", "gl_FragColor = vec4(diffuseColor.a, 0.0, 0.0, 1.0);")
    }
  }
  material.defines = {
    ...(road ? { USE_ROAD_MAP: "" } : {}),
    ...(gridOrigin ? { USE_GRID: "" } : {}),
  }
  if (edgeOnly) {
    material.toneMapped = false
    // The line sits on the same tile tops the terrain's depth copy draws, so
    // pull it a touch forward; a hill in front is still far nearer and wins.
    material.polygonOffset = true
    material.polygonOffsetFactor = -1
    material.polygonOffsetUnits = -1
  }
  // The grid origin is baked into the shader source, so it has to be part of
  // the program key or two maps of different sizes would share one program.
  const gridKey = gridOrigin ? `${gridOrigin.x.toFixed(3)}:${gridOrigin.z.toFixed(3)}` : "nogrid"
  material.customProgramCacheKey = () => `tiles-${road ? "road" : "ground"}-${gridKey}-forest-floor-sprite-atlas-v11${edgeOnly ? "-edge" : ""}${tileCoverage ? "-coverage" : ""}`
  return material
}

/** Presentation-only coverage, sampled at tile centres in every terrain pass.
 * Keeps previews on the live ground shader without changing its surface artwork. */
function tileCoverageShader(shader: Parameters<THREE.Material["onBeforeCompile"]>[0], texture: THREE.DataTexture) {
  shader.uniforms.tileCoverage = { value: texture }
  shader.uniforms.tileCoverageSize = { value: new THREE.Vector2(texture.image.width, texture.image.height) }
  shader.vertexShader = `uniform sampler2D tileCoverage;
uniform vec2 tileCoverageSize;
varying float vTileCoverage;\n` + shader.vertexShader
  shader.vertexShader = shader.vertexShader.replace("#include <begin_vertex>", `#include <begin_vertex>
    vTileCoverage = texture2D(tileCoverage, instanceMatrix[3].xz / tileCoverageSize + .5).r;`)
  shader.fragmentShader = "varying float vTileCoverage;\n" + shader.fragmentShader
  shader.fragmentShader = shader.fragmentShader
    .replace("#include <clipping_planes_fragment>", "#include <clipping_planes_fragment>\nif (vTileCoverage < .001) discard;")
    .replace("#include <opaque_fragment>", "diffuseColor.a *= vTileCoverage;\n#include <opaque_fragment>")
}

/**
 * Attach the per-instance data makeTileMaterial reads: `aSurface.x` and
 * `aOverlay` on every tile. A road geometry also carries which sides face
 * open land, its filled corners and junction shoulders, where traffic puts
 * the rut edges, and what the land here looks like (grass overlay and grain).
 */
function addTileAttributes(geometry: THREE.BufferGeometry, slots: number, road: boolean): void {
  const n = Math.max(1, slots)
  geometry.setAttribute("aCorners", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
  // Pack land flags, water and segment range into one attribute alongside elevation data.
  geometry.setAttribute("aSurface", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
  geometry.setAttribute("aOverlay", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
  if (!road) {
    geometry.setAttribute("aCut", new THREE.InstancedBufferAttribute(new Float32Array(n), 1))
    geometry.setAttribute("aShoreCorners", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
    geometry.setAttribute("aShorePaint", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
  }
  if (road) {
    geometry.setAttribute("aRoadOpen", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
    geometry.setAttribute("aRoadCorners", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
    geometry.setAttribute("aRoadShoulders", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
    geometry.setAttribute("aLandOverlay", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
    // Grain and the two rut edges packed together: vertex attributes are a
    // scarce resource (16 is a common limit) and the instance matrix alone
    // takes four.
    geometry.setAttribute("aLand", new THREE.InstancedBufferAttribute(new Float32Array(n * 4), 4))
  }
}

/** Unit box for flat tiles, with the per-instance tile data. */
function makeTileGeometry(slots: number, road = false): THREE.BoxGeometry {
  const geometry = new THREE.BoxGeometry(1, 1, 1)
  addTileAttributes(geometry, slots, road)
  return geometry
}

/**
 * How the ground mesh paints one land tile — everything but the grain. Sward
 * tiles (see SWARD_OVERLAY) wear the grass texture: `color` is white and the
 * tile's own colour and the shade ramp are folded into one `overlay` tint and
 * opacity. Everything else is a flat `color`, already pulled along the ramp.
 * The road mesh asks the same question about the land around a road tile, so
 * the grass and verge it shows are exactly what the ground would have been.
 */
interface LandPaint {
  sward: boolean
  color: THREE.Color
  overlay: THREE.Vector4
}

/** Scratch colours for paintLand. */
const landScratch = {
  own: new THREE.Color(),
  grass: new THREE.Color(TERRAIN.grass.color),
  water: WATER_DEPTH_COLORS.map((c) => new THREE.Color(c)),
}

function paintLand(
  map: GameMap,
  terrain: TerrainId,
  x: number,
  z: number,
  tint: THREE.Color,
  out: LandPaint,
): LandPaint {
  // A bridge tile is the water still running beneath it; the deck above is
  // its own mesh (see bridges.tsx).
  const def = TERRAIN[terrain === "bridge" ? "water" : isWoods(terrain) ? "grass" : terrain]
  const index = z * map.width + x
  const overlay = SWARD_OVERLAY[terrain]
  if (overlay === undefined) {
    // Flat-coloured ground, pulled along the shade ramp.
    if (def.id === "water") {
      // Water colours by depth — shallow shoreline light, deep water dark.
      // Hand-authored maps carry no depth data and render as shallow.
      const waterDepth = Math.min(MAX_WATER_DEPTH, Math.max(1, map.water?.depth[index] ?? 1))
      out.color.copy(landScratch.water[waterDepth - 1])
    } else {
      out.color.set(def.color)
    }
    out.color.lerp(tint, def.shadeBlend)
    out.overlay.set(0, 0, 0, 0)
    out.sward = false
    return out
  }

  // Sward: the texture carries the colour. Two layers land on it — the
  // tile's own colour at `overlay`, then the shade ramp at `shadeBlend` —
  // folded into one tint and opacity for the shader.
  out.color.setRGB(1, 1, 1)
  const own = landScratch.own.set(def.color)
  const a = overlay
  const b = def.shadeBlend
  const k = 1 - (1 - a) * (1 - b)
  if (k > 0) {
    const wa = (a * (1 - b)) / k
    const wb = b / k
    out.overlay.set(
      own.r * wa + tint.r * wb,
      own.g * wa + tint.g * wb,
      own.b * wa + tint.b * wb,
      k,
    )
  } else {
    out.overlay.set(0, 0, 0, 0)
  }
  out.sward = true
  return out
}

/** The 8 tiles around a road tile, with the 4 edge-sharing sides first, in +x, -x, +z, -z order to match roadEdge. */
const AROUND: ReadonlyArray<readonly [number, number]> = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
  [1, 1],
  [1, -1],
  [-1, 1],
  [-1, -1],
]

const NO_TREES: readonly TreePlacement[] = []

type TerrainProps = {
  map: GameMap
  /** Optional per-tile red-channel opacity for a decorative terrain footprint. */
  tileCoverage?: THREE.DataTexture
  /** Omit the deep earth slab for an isolated terrain preview. */
  slab?: boolean
  /** The rendered stand, with stable indices shared by the felling store. */
  trees?: readonly TreePlacement[]
  /** Simulation removals only; hiding the tree display leaves canopy shade intact. */
  felledTrees?: ReadonlySet<number>
  /** Road development tier — index into ROAD_TIERS. */
  roadTier?: number
  /** Travelers on the main road; wears its surface (see roadWear). */
  traffic?: number
  /** Travelers who turn aside for the relic; wears the track to it. */
  relicTraffic?: number
  /** Tunable look of the road surface. */
  look?: RoadLook
  /** Draw the global tile lattice over the ground. Off by default. */
  showGrid?: boolean
  /** Optional snapshot of actual traveled segments and their individual compaction. */
  traveledRoads?: ReadonlyMap<number, readonly RoadSegment[]>
  /** Live game roads lose their inherited surface when walkers stop using them. */
  regrowRoads?: boolean
}
interface TerrainShared {
  coveredLand: Set<number>
  floors: ReturnType<typeof dirtFloorMask>
  floorTexture: THREE.DataTexture
  shoulders: ReturnType<typeof junctionShoulders>
  grain: Float64Array
  floor: number
}
interface TerrainSurfaces extends TerrainShared {
  treeGround: TileMaterialOptions["treeGround"]
  growth: { texture: THREE.DataTexture; origin: THREE.Vector2 }
  palette: THREE.DataTexture
  waterPalette: THREE.DataTexture
  cuts: ReadonlyMap<number, CliffCorner>
  hiddenFaces: Uint8Array
  turbulence: Float32Array
}

const TerrainContext = createContext<TerrainSurfaces>(null!)

/** Static land is batched in spatial blocks. Each road snapshot only
 * repaints the blocks it changes; offscreen blocks are rejected in every pass. */
export function TerrainTiles(props: TerrainProps) {
  const { map, trees = NO_TREES, felledTrees } = props
  const forestFloor = useTerrainTexture("/textures/forest-floors-v2.png", "#73633f")
  const edgeGrain = useTerrainTexture(TERRAIN_EDGE_GRAIN_URL, "#808080")
  useMemo(() => {
    forestFloor.wrapS = forestFloor.wrapT = THREE.RepeatWrapping
    forestFloor.magFilter = THREE.NearestFilter
    forestFloor.minFilter = THREE.NearestFilter
    forestFloor.generateMipmaps = false
    edgeGrain.colorSpace = THREE.NoColorSpace
    edgeGrain.wrapS = edgeGrain.wrapT = THREE.RepeatWrapping
    edgeGrain.minFilter = edgeGrain.magFilter = THREE.NearestFilter
    edgeGrain.generateMipmaps = false
    edgeGrain.needsUpdate = true
  }, [forestFloor, edgeGrain])
  const shadowAtlas = useTerrainTexture(TREE_GROUND_ATLAS, "#000000")
  useMemo(() => {
    shadowAtlas.colorSpace = THREE.NoColorSpace
    shadowAtlas.minFilter = shadowAtlas.magFilter = THREE.NearestFilter
    shadowAtlas.generateMipmaps = false
    shadowAtlas.needsUpdate = true
  }, [shadowAtlas])
  const treeGround = useMemo(() => {
    const field = treeGroundField(map, trees, felledTrees)
    const texture = new THREE.DataTexture(field.data, field.width, field.height)
    texture.minFilter = texture.magFilter = THREE.NearestFilter
    texture.needsUpdate = true
    return { texture, atlas: shadowAtlas, floor: forestFloor, grain: edgeGrain, size: new THREE.Vector2(map.width, map.depth) }
  }, [map.tiles, map.width, map.depth, map.shortcuts, map.darkForests, map.darkForestFloor, trees, felledTrees, shadowAtlas, forestFloor, edgeGrain])
  useEffect(() => () => treeGround.texture.dispose(), [treeGround])

  const tier = ROAD_TIERS[clampRoadTier(props.roadTier ?? DEFAULT_ROAD_TIER)]
  const grain = useMemo(() => {
    const rng = makeRng(deriveSeed(map.seed ?? 0, SEED_STREAM.tileJitter))
    return Float64Array.from({ length: map.width * map.depth }, () => rng() - .5)
  }, [map.tiles, map.width, map.depth, map.seed])
  const previousLandscape = useRef<Pick<TerrainShared, "coveredLand" | "shoulders" | "grain">>(undefined)
  const landscape = useMemo(() => {
    const bridges = bridgeLayout(map), old = previousLandscape.current
    let coveredLand = new Set([...bridges.connectors, ...bridges.ramps].map(t => t.z * map.width + t.x))
    if (old && old.coveredLand.size === coveredLand.size && [...coveredLand].every(i => old.coveredLand.has(i))) coveredLand = old.coveredLand
    let shoulders = junctionShoulders(map, coveredLand)
    if (old && old.shoulders.size === shoulders.size && [...shoulders].every(([i, flags]) => flags.every((flag, side) => old.shoulders.get(i)?.[side] === flag))) shoulders = old.shoulders
    const next = old && old.coveredLand === coveredLand && old.shoulders === shoulders && old.grain === grain
      ? old : { coveredLand, shoulders, grain }
    previousLandscape.current = next
    return next
  }, [map, grain])
  const floors = useMemo(() => dirtFloorMask(map), [map.tiles, map.width, map.depth, map.buildings, map.elevation, map.water, map.site])
  const floorTexture = useMemo(() => new THREE.DataTexture(new Uint8Array(map.width * map.depth * 4), map.width, map.depth), [map.width, map.depth])
  useLayoutEffect(() => { floorTexture.image.data = floors.data; floorTexture.needsUpdate = true }, [floorTexture, floors])
  useEffect(() => () => floorTexture.dispose(), [floorTexture])
  const floor = useMemo(() => (map.elevation?.height.reduce((a, b) => Math.min(a, b), SLAB_TOP) ?? SLAB_TOP) - .02, [map.elevation])
  const shared = useMemo<TerrainShared>(() => ({ ...landscape, floors, floorTexture, floor }), [landscape, floors, floorTexture, floor])
  const { coveredLand } = shared
  const growthField = useMemo(() => groundGrowthField(map), [map.tiles, map.width, map.depth, map.seed, map.buildings])
  const growth = useMemo(() => {
    const texture = new THREE.DataTexture(new Uint8Array(growthField.data.length), growthField.width, growthField.height)
    return { texture, origin: new THREE.Vector2(...growthField.origin) }
  }, [growthField.width, growthField.height, map.width, map.depth])
  useLayoutEffect(() => { growth.texture.image.data = growthField.data; growth.texture.needsUpdate = true }, [growth, growthField])
  useEffect(() => () => growth.texture.dispose(), [growth])

  const palette = useMemo(() => {
    const data = new Float32Array(map.width * map.depth * 4)
    const rng = makeRng(deriveSeed(map.seed ?? 0, SEED_STREAM.tileJitter))
    const tint = new THREE.Color(), color = new THREE.Color()
    const paint: LandPaint = { sward: false, color: new THREE.Color(), overlay: new THREE.Vector4() }
    const surfaces = map.tiles.map((original, i): TerrainId => {
      const x = i % map.width, z = Math.floor(i / map.width)
      if (coveredLand.has(i) || isRoadTerrain(original)) return "grass"
      // Wet records supply bank colours for the existing shoreline insets.
      if (original === "water" || original === "bridge") {
        const corner = shorelineCorners(map, x, z).findIndex(Boolean)
        if (corner >= 0) return map.tiles[z * map.width + x + SHORE_CORNERS[corner][0]]
        return AROUND.some(([dx, dz]) => tileAt(map, x + dx, z + dz) === "sand") ? "sand" : "grass"
      }
      return original
    })
    const corners = groundCornerTiles(map, surfaces)
    for (let z = 0; z < map.depth; z++) for (let x = 0; x < map.width; x++) {
      const i = z * map.width + x, terrain = surfaces[i]
      tint.copy(OPEN_MEADOW_TINT)
      paintLand(map, terrain, x, z, tint, paint)
      color.copy(paint.color)
      if (paint.sward) {
        const { x: r, y: g, z: b, w: a } = paint.overlay
        color.setRGB(1 + (r / landScratch.grass.r - 1) * a,
          1 + (g / landScratch.grass.g - 1) * a, 1 + (b / landScratch.grass.b - 1) * a)
      }
      color.multiplyScalar(1 + (rng() - .5) * TERRAIN[terrain].jitter)
      data.set([color.r, color.g, color.b, groundPaintCode(terrain, corners[i])], i * 4)
    }
    const texture = new THREE.DataTexture(data, map.width, map.depth, THREE.RGBAFormat, THREE.FloatType)
    texture.needsUpdate = true
    return texture
  }, [map.tiles, map.width, map.depth, map.seed, map.water, coveredLand])
  useEffect(() => () => palette.dispose(), [palette])
  const waterPalette = useMemo(() => {
    const data = new Float32Array(map.tiles.length * 4), corners = waterDepthCorners(map)
    const rng = makeRng(deriveSeed(map.seed ?? 0, SEED_STREAM.tileJitter))
    const tint = new THREE.Color()
    const paint: LandPaint = { sward: false, color: new THREE.Color(), overlay: new THREE.Vector4() }
    for (let i = 0; i < map.tiles.length; i++) {
      tint.copy(OPEN_MEADOW_TINT)
      paintLand(map, "water", i % map.width, Math.floor(i / map.width), tint, paint)
      paint.color.multiplyScalar(1 + (rng() - .5) * TERRAIN.water.jitter)
      const wet = map.tiles[i] === "water" || map.tiles[i] === "bridge"
      const shore = shorelineCorners(map, i % map.width, Math.floor(i / map.width)).reduce((bits, flag, c) => bits + flag * 2 ** c, 0)
      data.set([paint.color.r, paint.color.g, paint.color.b, corners[i] + 1 + (wet ? 8 : 0) + shore * 16], i * 4)
    }
    const texture = new THREE.DataTexture(data, map.width, map.depth, THREE.RGBAFormat, THREE.FloatType)
    texture.needsUpdate = true
    return texture
  }, [map.tiles, map.width, map.depth, map.seed, map.water])
  useEffect(() => () => waterPalette.dispose(), [waterPalette])
  const cuts = useMemo(() => {
    const cuts = new Map<number, CliffCorner>()
    for (let z = 0; z < map.depth; z++) for (let x = 0; x < map.width; x++) {
      const cut = terrainCorner(map, x, z)
      if (cut && !coveredLand.has(z * map.width + x)) cuts.set(z * map.width + x, cut)
    }
    return cuts
  }, [map, coveredLand])
  const hiddenFaces = useMemo(() => terrainHiddenFaces(map, cuts), [map, cuts])
  const turbulence = useMemo(() => waterfallTurbulence(map.water, map.tiles.length, map.elevation?.settings.turbulenceReach ?? DEFAULT_ELEVATION.turbulenceReach), [map.water, map.tiles.length, map.elevation?.settings.turbulenceReach])
  const surfaces = useMemo(() => ({ ...shared, turbulence, treeGround, growth, palette, waterPalette, cuts, hiddenFaces }), [shared, turbulence, treeGround, growth, palette, waterPalette, cuts, hiddenFaces])
  const blocks = useMemo(() => terrainBlocks(map.width, map.depth), [map.width, map.depth])
  const blockState = useRef<TerrainBlockState>(undefined)
  const revisions = useMemo(() => {
    blockState.current = terrainBlockState(map, blocks, blockState.current)
    return blockState.current.revisions
  }, [map, blocks])
  const founding = useMemo(() => diagonalRoadSegments(map, coveredLand), [map, coveredLand])
  const blockForTile = useMemo(() => {
    const across = Math.ceil(map.width / TERRAIN_BLOCK)
    return (tile: number) => blocks[Math.floor(Math.floor(tile / map.width) / TERRAIN_BLOCK) * across + Math.floor((tile % map.width) / TERRAIN_BLOCK)].id
  }, [map.width, blocks])
  const inheritedRoads = useMemo(() => {
    const grouped = new Map<number, number[]>()
    for (let tile = 0; tile < map.tiles.length; tile++) {
      if (!isRoadTerrain(map.tiles[tile]) && !shared.shoulders.has(tile)) continue
      const key = blockForTile(tile), list = grouped.get(key) ?? []
      list.push(tile); grouped.set(key, list)
    }
    return grouped
  }, [map.tiles, landscape, blockForTile])
  const previous = useRef(new Map<number, { roads: Map<number, readonly RoadSegment[]>; wear: number[] }>())
  const snapshots = useMemo(() => {
    const source = props.traveledRoads ?? founding
    const grouped = new Map<number, Map<number, readonly RoadSegment[]>>()
    for (const [tile, segments] of source) {
      const key = blockForTile(tile), roads = grouped.get(key) ?? new Map<number, readonly RoadSegment[]>()
      roads.set(tile, segments); grouped.set(key, roads)
    }
    const next = new Map<number, { roads: Map<number, readonly RoadSegment[]>; wear: number[] }>()
    for (const block of blocks) {
      const roads = grouped.get(block.id) ?? new Map<number, readonly RoadSegment[]>(), wear: number[] = []
      for (const index of new Set([...(inheritedRoads.get(block.id) ?? []), ...roads.keys()])) {
        wear.push(index, foundingRoadStrength(map, index), foundingRoadTraffic(map, index, props.traffic ?? DEFAULT_TRAFFIC))
      }
      const old = previous.current.get(block.id)
      next.set(block.id, old && sameRoadSnapshot(old, { roads, wear }) ? old : { roads, wear })
    }
    previous.current = next
    return next
  }, [map, blocks, inheritedRoads, blockForTile, founding, props.traveledRoads, props.traffic])
  // Texture requests never suspend the terrain: colored surfaces are already
  // in place while each image loads, including when switching road tiers.
  const roadTexture = useTerrainTexture(tier.textureUrl, TERRAIN.path.color)
  const trailTexture = useTerrainTexture(ROAD_TIERS[0].textureUrl, TERRAIN.path.color)
  const grass = useTerrainTexture(GRASS_TEXTURE_URL, TERRAIN.grass.color)
  const ground = useTerrainTexture("/textures/ground.png", "#ffffff")
  const sand = useTerrainTexture("/textures/sand.png", TERRAIN.sand.color)
  useMemo(() => {
    for (const texture of [roadTexture, trailTexture, grass, ground, sand]) {
      texture.colorSpace = THREE.SRGBColorSpace
      texture.wrapS = THREE.RepeatWrapping
      texture.wrapT = THREE.RepeatWrapping
      texture.magFilter = THREE.NearestFilter
      texture.minFilter = THREE.NearestMipmapLinearFilter
    }
  }, [roadTexture, trailTexture, grass, ground, sand])

  const dirt = useTerrainTexture(DIRT_TEXTURE_URL, TERRAIN.dirt.color)
  useMemo(() => {
    dirt.colorSpace = THREE.SRGBColorSpace
    // Repeat around the cliff, but run the topsoil-to-subsoil ramp just once
    // top to bottom, so wrap horizontally and clamp vertically.
    dirt.wrapS = THREE.RepeatWrapping
    dirt.wrapT = THREE.ClampToEdgeWrapping
    dirt.repeat.set(map.width / 4, 1)
    dirt.anisotropy = 4
  }, [dirt, map])

  const textures = useMemo(() => ({ roadTexture, trailTexture, grass, ground, sand, dirt }), [roadTexture, trailTexture, grass, ground, sand, dirt])
  const slabPosition: [number, number, number] = [0, shared.floor - SLAB_THICKNESS / 2, 0]
  const slabArgs: [number, number, number] = [map.width + SLAB_EXPAND, SLAB_THICKNESS, map.depth + SLAB_EXPAND]
  return <group name="terrain">
    {props.slab !== false && <>
      <mesh position={slabPosition}><boxGeometry args={slabArgs} /><meshLambertMaterial map={dirt} /></mesh>
      <mesh position={slabPosition} layers-mask={OUTLINE_ID_LAYER_MASK}><boxGeometry args={slabArgs} /><meshBasicMaterial color="black" toneMapped={false} /></mesh>
    </>}
    <TerrainMapContext.Provider value={map}><TerrainContext.Provider value={surfaces}>{blocks.map((bounds, index) => <TerrainTileBlock key={bounds.id}
      roadTier={props.roadTier} traffic={props.traffic} relicTraffic={props.relicTraffic} look={props.look} showGrid={props.showGrid}
      tileCoverage={props.tileCoverage}
      regrowRoads={props.regrowRoads} bounds={bounds} revision={revisions[index]} textures={textures}
      traveledRoads={snapshots.get(bounds.id)!.roads} wear={snapshots.get(bounds.id)!.wear} />)}</TerrainContext.Provider></TerrainMapContext.Provider>
  </group>
}

const TerrainTileBlock = memo(function TerrainTileBlock({
  tileCoverage,
  roadTier = DEFAULT_ROAD_TIER, traffic = DEFAULT_TRAFFIC, relicTraffic = traffic,
  look = DEFAULT_ROAD_LOOK, showGrid = false, traveledRoads, regrowRoads = false, bounds, revision, textures, wear: wearSnapshot,
}: Omit<TerrainProps, "map"> & { bounds: TerrainBlockBounds; revision: object; textures: { roadTexture: THREE.Texture; trailTexture: THREE.Texture; grass: THREE.Texture; ground: THREE.Texture; sand: THREE.Texture; dirt: THREE.Texture }; wear: number[] }) {
  const map = useContext(TerrainMapContext)!
  const shared = useContext(TerrainContext)
  const { roadTexture, trailTexture, grass, ground, sand, dirt } = textures
  const groundMeshRef = useRef<THREE.InstancedMesh>(null)
  const roadMeshRef = useRef<THREE.InstancedMesh>(null)
  const edgeMeshRef = useRef<THREE.InstancedMesh>(null)
  const idMeshRef = useRef<THREE.InstancedMesh>(null)
  const count = (bounds.endX - bounds.x) * (bounds.endZ - bounds.z)

  const { coveredLand, floors, floorTexture, shoulders, treeGround, grain: grains, floor, growth, palette, waterPalette, cuts, hiddenFaces } = shared
  const tier = ROAD_TIERS[clampRoadTier(roadTier)]
  const diagonalSegments = useMemo(() => {
    const segments = traveledRoads
      ? new Map([...traveledRoads].filter(([index]) => !coveredLand.has(index)))
      : diagonalRoadSegments(map, coveredLand)
    if (regrowRoads && !tier.paved) for (const [index, roads] of segments) {
      const opacity = foundingRoadStrength(map, index)
      segments.set(index, roads.map(s => s[4] < 2 || s[4] === 3 ? [s[0], s[1], s[2], s[3], s[4], opacity] : s))
    }
    return segments
  }, [revision, coveredLand, traveledRoads, regrowRoads, tier.paved, wearSnapshot])
  const segmentData = useMemo(() => {
    const count = [...diagonalSegments.values()].reduce((sum, segments) => sum + segments.length * 2, 0)
    const data = new Float32Array(Math.max(1, count) * 4)
    const ranges = new Map<number, [number, number]>()
    let offset = 0
    for (const [index, segments] of diagonalSegments) {
      ranges.set(index, [offset, segments.length])
      for (const segment of segments) {
        data.set([segment[0], segment[1], segment[2], segment[3]], offset * 4)
        data.set(roadSegmentWear(segment, regrowRoads ? foundingRoadTraffic(map, index, traffic) : traffic, regrowRoads ? foundingRoadTraffic(map, index, relicTraffic) : relicTraffic, tier.tier), (offset + 1) * 4)
        offset += 2
      }
    }
    return { data, ranges }
  }, [diagonalSegments, traffic, relicTraffic, tier.tier, revision, regrowRoads])
  const segmentTexture = useMemo(() => new RoadSegmentTexture(), [])
  useEffect(() => () => segmentTexture.dispose(), [segmentTexture])
  const cliffCuts = useMemo(() => {
    const cuts = new Map<number, CliffCorner>()
    for (let z = bounds.z; z < bounds.endZ; z++) for (let x = bounds.x; x < bounds.endX; x++) {
      const cut = shared.cuts.get(z * map.width + x)
      if (cut) cuts.set(z * map.width + x, cut)
    }
    return cuts
  }, [revision, bounds])
  const geometryCount = count + cliffCuts.size
  const segmentUniforms = useMemo(() => ({ texture: { value: null as THREE.DataTexture | null }, size: { value: new THREE.Vector2() } }), [])
  useLayoutEffect(() => {
    const texture = segmentTexture.update(segmentData.data)
    segmentUniforms.texture.value = texture
    segmentUniforms.size.value.set(texture.image.width, texture.image.height)
  }, [segmentData, segmentTexture, segmentUniforms])
  const previousRoadTiles = useRef<number[]>([])
  const roadTiles = useMemo(() => {
    const tiles: number[] = []
    for (let z = bounds.z; z < bounds.endZ; z++) for (let x = bounds.x; x < bounds.endX; x++) {
      const i = z * map.width + x
      if ((isRoadTerrain(map.tiles[i]) || shoulders.has(i) || diagonalSegments.has(i) || floors.tiles.has(i)) && !coveredLand.has(i) && !cliffCuts.has(i)) tiles.push(i)
    }
    const previous = previousRoadTiles.current
    if (previous.length !== tiles.length || tiles.some((tile, i) => tile !== previous[i])) previousRoadTiles.current = tiles
    return previousRoadTiles.current
  }, [revision, bounds, coveredLand, shoulders, diagonalSegments, cliffCuts])
  const roadCount = roadTiles.length
  const roadTileSet = useMemo(() => new Set(roadTiles), [roadTiles])

  // The look is uniforms shared with the material: tuned in place, no recompile.
  const dpr = useThree((s) => s.viewport.dpr)
  const lookUniforms = useMemo<RoadLookUniforms>(
    () => ({
      opacity: { value: DEFAULT_ROAD_LOOK.opacity },
      shade: { value: DEFAULT_ROAD_LOOK.shade },
      edgeLine: { value: DEFAULT_ROAD_LOOK.edgeLine },
      edgeWidth: { value: DEFAULT_ROAD_LOOK.edgeWidth },
      pixelRatio: { value: 1 },
    }),
    [],
  )
  useEffect(() => {
    lookUniforms.opacity.value = look.opacity
    lookUniforms.shade.value = look.shade
    lookUniforms.edgeLine.value = look.edgeLine
    lookUniforms.edgeWidth.value = look.edgeWidth
    lookUniforms.pixelRatio.value = dpr
  }, [lookUniforms, look, dpr])
  useFrame(({ scene }) => {
    lookUniforms.edgeLine.value = sceneryDetail(scene) === 0 ? look.edgeLine : 0
    if (process.env.NEXT_PUBLIC_GAME_BENCHMARK === "1") {
      const shown = benchmarkWork.pathDrawing
      if (roadMeshRef.current) {
        roadMeshRef.current.material = shown ? roadMaterial : groundMaterial
        roadMeshRef.current.userData.pathsVisible = shown
      }
      if (edgeMeshRef.current) edgeMeshRef.current.visible = shown && roadCount > 0
    }
  })

  // Tile boundaries sit at integer offsets from -width/2, so the lattice
  // origin is that half-extent modulo one tile.
  const gridOrigin = useMemo(
    () => (showGrid ? { x: (map.width / 2) % 1, z: (map.depth / 2) % 1 } : undefined),
    [showGrid, map.width, map.depth],
  )
  const groundMaterial = useMemo(
    () => makeTileMaterial({ grassTexture: grass, groundTexture: ground, sandTexture: sand, palette, waterPalette, growth, treeGround, cliffTexture: dirt, gridOrigin, tileCoverage }),
    [grass, ground, sand, palette, waterPalette, growth, treeGround, dirt, gridOrigin, tileCoverage],
  )
  useEffect(() => () => groundMaterial.dispose(), [groundMaterial])
  const roadMaterial = useMemo(
    () =>
      makeTileMaterial({
        tileCoverage,
        grassTexture: grass,
        groundTexture: ground,
        sandTexture: sand,
        palette,
        waterPalette,
        growth,
        treeGround,
        cliffTexture: dirt,
        gridOrigin,
        road: { texture: roadTexture, edgeWear: tier.edgeWear, look: lookUniforms, segments: segmentUniforms, floors: floorTexture, trail: trailTexture, isDirt: tier.tier === 0 },
      }),
    [grass, ground, sand, palette, waterPalette, growth, treeGround, dirt, gridOrigin, roadTexture, trailTexture, tier, lookUniforms, segmentUniforms, floorTexture, tileCoverage],
  )
  useEffect(() => () => roadMaterial.dispose(), [roadMaterial])
  // The same road surface reduced to its edge line, for the outline pass.
  const edgeMaterial = useMemo(
    () =>
      makeTileMaterial({
        tileCoverage,
        grassTexture: grass,
        groundTexture: ground,
        sandTexture: sand,
        palette,
        waterPalette,
        growth,
        treeGround,
        cliffTexture: dirt,
        gridOrigin,
        road: { texture: roadTexture, edgeWear: tier.edgeWear, look: lookUniforms, segments: segmentUniforms, floors: floorTexture, trail: trailTexture, isDirt: tier.tier === 0 },
        edgeOnly: true,
      }),
    [grass, ground, sand, palette, waterPalette, growth, treeGround, dirt, gridOrigin, roadTexture, trailTexture, tier, lookUniforms, segmentUniforms, floorTexture, tileCoverage],
  )
  useEffect(() => () => edgeMaterial.dispose(), [edgeMaterial])
  const idGeometry = useMemo(() => makeTileGeometry(geometryCount), [geometryCount])
  const idMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({ color: "black", toneMapped: false })
    material.onBeforeCompile = shader => {
      elevationShader(shader)
      if (tileCoverage) tileCoverageShader(shader, tileCoverage)
    }
    material.customProgramCacheKey = () => `terrain-id${tileCoverage ? "-coverage" : ""}`
    return material
  }, [tileCoverage])
  useEffect(() => () => { idGeometry.dispose(); idMaterial.dispose() }, [idGeometry, idMaterial])

  const groundGeometry = useMemo(() => makeTileGeometry(geometryCount - roadCount), [geometryCount, roadCount])
  useEffect(() => () => groundGeometry.dispose(), [groundGeometry])

  const roadGeometry = useMemo(() => makeTileGeometry(roadCount, true), [roadCount])
  useEffect(() => () => roadGeometry.dispose(), [roadGeometry])

  useLayoutEffect(() => {
    const groundMesh = groundMeshRef.current
    const roadMesh = roadMeshRef.current
    const edgeMesh = edgeMeshRef.current
    const idMesh = idMeshRef.current
    if (!groundMesh || !roadMesh || !edgeMesh || !idMesh) {
      return
    }

    const matrix = new THREE.Matrix4()
    const position = new THREE.Vector3()
    const quaternion = new THREE.Quaternion()
    const scale = new THREE.Vector3()
    const color = new THREE.Color()
    const tint = new THREE.Color()
    const neighbourTint = new THREE.Color()
    const land: LandPaint = { sward: false, color: new THREE.Color(), overlay: new THREE.Vector4() }
    const landOverlay = new THREE.Vector4()

    // Each tile writes to its flat ground material; bridge surfaces sit above it.
    const attr = (geometry: THREE.BufferGeometry, name: string) =>
      geometry.getAttribute(name) as THREE.InstancedBufferAttribute
    const roadTargets = [roadMesh].map((mesh) => {
      const geometry = roadGeometry
      return {
        mesh,
        next: 0,
        open: attr(geometry, "aRoadOpen"),
        roadCorners: attr(geometry, "aRoadCorners"),
        shoulders: attr(geometry, "aRoadShoulders"),
        surface: attr(geometry, "aSurface"),
        landOverlay: attr(geometry, "aLandOverlay"),
        land: attr(geometry, "aLand"),
        corners: attr(geometry, "aCorners"),
        overlay: attr(geometry, "aOverlay"),
      }
    })
    const groundTargets = [groundMesh].map((mesh) => {
      const geometry = groundGeometry
      return {
        mesh,
        next: 0,
        surface: attr(geometry, "aSurface"),
        corners: attr(geometry, "aCorners"),
        overlay: attr(geometry, "aOverlay"),
        cut: attr(geometry, "aCut"),
        shoreCorners: attr(geometry, "aShoreCorners"),
        shorePaint: attr(geometry, "aShorePaint"),
      }
    })

    // Colour grain is a function of the map's own seed, one stream per consumer.
    // One draw per tile in scan order, whichever mesh the tile lands in, so the
    // grain never reshuffles when the road tier changes.

    let localIndex = 0, lowerId = count
    for (let z = bounds.z; z < bounds.endZ; z++) {
      for (let x = bounds.x; x < bounds.endX; x++) {
        const index = z * map.width + x
        const cut = cliffCuts.get(index)
        const terrain = coveredLand.has(index) ? "grass" : map.tiles[index]
        // A bridge tile draws the water still running beneath it (see paintLand).
        const def = TERRAIN[terrain === "bridge" ? "water" : isWoods(terrain) ? "grass" : terrain]
        const grain = grains[index]
        const jitter = 1 + grain * def.jitter
        const corners = map.elevation?.corners.slice(index * 4, index * 4 + 4) ?? [0, 0, 0, 0]
        const top = TILE_HEIGHT + Math.max(...corners)
        const height = top - floor
        position.set(tileToWorldX(map, x), floor + height / 2, tileToWorldZ(map, z))
        scale.set(1, height, 1)
        matrix.compose(position, quaternion, scale)
        idMesh.setMatrixAt(localIndex, matrix)
        attr(idGeometry, "aCorners").setXYZW(localIndex, corners[0], corners[1], corners[2], corners[3])
        attr(idGeometry, "aSurface").setY(localIndex, hiddenFaces[index] * 2)
        attr(idGeometry, "aCut").setX(localIndex++, cut ? cut.corner + 1 : 0)

        tint.copy(OPEN_MEADOW_TINT)

        if (roadTileSet.has(index)) {
          const shoulderOnly = !isRoadTerrain(terrain)
          // The texture carries the road's colour; the instance carries the
          // weathering from whatever surrounds this stretch, plus the grain.
          const [r, g, b] = roadTint(map, x, z, !isRoadTerrain(terrain) && floors.tiles.has(index) ? 0 : tier.tier)
          color.setRGB(r, g, b, THREE.SRGBColorSpace)
          color.multiplyScalar(jitter)

          // Paths always sit on grass. Borrow only surrounding grass tints;
          // water, sand, and bare earth must never replace the grassy base.
          const edge = roadEdge(map, x, z)
          landOverlay.set(0, 0, 0, 0)
          let swardAround = 0
          for (let side = 0; side < AROUND.length; side++) {
            const [dx, dz] = AROUND[side]
            const neighbour = tileAt(map, x + dx, z + dz)
            if (roadContinues(neighbour)) continue
            const nx = x + dx
            const nz = z + dz
            paintLand(map, neighbour, nx, nz, neighbourTint.copy(OPEN_MEADOW_TINT), land)
            if (land.sward) {
              landOverlay.add(land.overlay)
              swardAround++
            }
          }
          if (swardAround > 0) landOverlay.divideScalar(swardAround)
          else landOverlay.copy(paintLand(map, "grass", x, z, tint, land).overlay)
          if (shoulderOnly) {
            paintLand(map, terrain, x, z, tint, land)
            if (land.sward) landOverlay.copy(land.overlay)
            else landOverlay.set(land.color.r, land.color.g, land.color.b, 1)
          }
          // The grain a land tile here would have had, from the same draw
          // (under the same canopy), and the rut edges for this road's own
          // traffic.
          const landJitter = 1 + grain * TERRAIN.grass.jitter

          {
            const target = roadTargets[0]
            const i = target.next++
            target.surface.setY(i, hiddenFaces[index] * 2)
            target.corners.setXYZW(i, corners[0], corners[1], corners[2], corners[3])
            target.mesh.setMatrixAt(i, matrix)
            target.mesh.setColorAt(i, color)
            // The edge copy shares the road geometry and its instance data;
            // only the transform lives on the mesh.
            edgeMesh.setMatrixAt(i, matrix)
            target.overlay.setXYZW(i, tint.r, tint.g, tint.b, shoulderOnly ? TERRAIN.path.shadeBlend : def.shadeBlend)
            // -1 is a diagonal entrance, 0 an ordinary entrance, 1 open land.
            target.open.setXYZW(i, edge.open[0] - edge.diagonal[0], edge.open[1] - edge.diagonal[1],
              edge.open[2] - edge.diagonal[2], edge.open[3] - edge.diagonal[3])
            target.roadCorners.setXYZW(i, ...edge.filledCorners)
            target.shoulders.setXYZW(i, ...(shoulders.get(index) ?? [0, 0, 0, 0]))
            const shoreCode = shoulderOnly ? shorelineCorners(map, x, z).reduce((code, flag, corner) => code + flag * 2 ** corner, 0) : 0
            target.surface.setX(i, shoulderOnly ? 1 + 2 * shoreCode : 0)
            target.landOverlay.setXYZW(i, landOverlay.x, landOverlay.y, landOverlay.z, landOverlay.w)
            target.land.setXYZW(i, landJitter, 0, 0, 0)
          }
          continue
        }

        paintLand(map, terrain, x, z, tint, land)
        color.copy(land.color).multiplyScalar(jitter)
        {
          const target = groundTargets[0]
          const i = target.next++
          target.surface.setY(i, hiddenFaces[index] * 2 + (map.water?.depth[index] || terrain === "water" || terrain === "bridge" ? 1 : 0))
          target.corners.setXYZW(i, corners[0], corners[1], corners[2], corners[3])
          target.mesh.setMatrixAt(i, matrix)
          target.mesh.setColorAt(i, color)
          target.surface.setX(i, land.sward ? 1 : 0)
          target.surface.setZ(i, 0)
          target.cut.setX(i, cut ? cut.corner + 1 : 0)
          target.overlay.setXYZW(i, land.overlay.x, land.overlay.y, land.overlay.z, land.overlay.w)
          const shoreCorners = coveredLand.has(index) || cut ? [0, 0, 0, 0] as const : shorelineCorners(map, x, z)
          target.shoreCorners.setXYZW(i, shoreCorners[0], shoreCorners[1], shoreCorners[2], shoreCorners[3])
          let bank: TerrainId = "water"
          if (terrain === "water") {
            bank = AROUND.some(([dx, dz]) => tileAt(map, x + dx, z + dz) === "sand") ? "sand" : "grass"
          }
          paintLand(map, bank, x, z, tint, land)
          if (land.sward) color.copy(tint)
          else color.copy(land.color)
          target.shorePaint.setXYZW(i, color.r, color.g, color.b, land.sward ? 1 : 0)
          if (cut) {
            const low = target.next++, id = lowerId++
            const h = TILE_HEIGHT + Math.max(...cut.lower) - floor
            position.y = floor + h / 2; scale.y = h
            matrix.compose(position, quaternion, scale)
            target.mesh.setMatrixAt(low, matrix); idMesh.setMatrixAt(id, matrix)
            target.corners.setXYZW(low, ...cut.lower); attr(idGeometry, "aCorners").setXYZW(id, ...cut.lower)
            target.cut.setX(low, -cut.corner - 1); attr(idGeometry, "aCut").setX(id, -cut.corner - 1)
            const source = map.tiles[cut.donor]
            paintLand(map, source, cut.donor % map.width, Math.floor(cut.donor / map.width), neighbourTint.copy(OPEN_MEADOW_TINT), land)
            color.copy(land.color).multiplyScalar(1 + grains[cut.donor] * TERRAIN[source].jitter)
            target.mesh.setColorAt(low, color)
            target.surface.setXYZW(low, land.sward ? 1 : 0, source === "water" ? 1 : 0, cut.donor + 1, 0)
            target.overlay.setXYZW(low, land.overlay.x, land.overlay.y, land.overlay.z, land.overlay.w)
            target.shoreCorners.setXYZW(low, 0, 0, 0, 0); target.shorePaint.setXYZW(low, 0, 0, 0, 0)
          }

        }
      }
    }

    for (const target of roadTargets) {
      target.mesh.instanceMatrix.needsUpdate = true
      if (target.mesh.instanceColor) target.mesh.instanceColor.needsUpdate = true
      target.open.needsUpdate = true
      target.roadCorners.needsUpdate = true
      target.shoulders.needsUpdate = true
      target.surface.needsUpdate = true
      target.landOverlay.needsUpdate = true
      target.land.needsUpdate = true
      target.corners.needsUpdate = true
      target.overlay.needsUpdate = true
    }
    for (const target of groundTargets) {
      target.mesh.instanceMatrix.needsUpdate = true
      if (target.mesh.instanceColor) target.mesh.instanceColor.needsUpdate = true
      target.surface.needsUpdate = true
      target.corners.needsUpdate = true
      target.overlay.needsUpdate = true
      target.cut.needsUpdate = true
      target.shoreCorners.needsUpdate = true
      target.shorePaint.needsUpdate = true
    }
    attr(idGeometry, "aCorners").needsUpdate = true
    attr(idGeometry, "aCut").needsUpdate = true
    attr(idGeometry, "aSurface").needsUpdate = true
    edgeMesh.instanceMatrix.needsUpdate = true
    idMesh.instanceMatrix.needsUpdate = true
    compactTerrainFaces(groundGeometry, groundMesh.count)
    compactTerrainFaces(roadGeometry, roadMesh.count)
    compactTerrainFaces(idGeometry, idMesh.count)
    // Recompute bounds after map edits for correct culling and picking.
    for (const target of [...roadTargets, ...groundTargets]) target.mesh.computeBoundingSphere()
    edgeMesh.computeBoundingSphere()
    idMesh.computeBoundingSphere()
  }, [
    revision,
    tier,
    roadGeometry,
    groundGeometry,
    cliffCuts,
    count,
    coveredLand,
    floor,
    idGeometry,
    shoulders,
    roadTileSet,
    bounds,
  ])

  // Wear changes frequently; land colors, terrain matrices and cliff bounds do
  // not. Upload only the road attributes unless a path enters a new tile.
  useLayoutEffect(() => {
    const land = roadGeometry.getAttribute("aLand") as THREE.InstancedBufferAttribute
    const surface = roadGeometry.getAttribute("aSurface") as THREE.InstancedBufferAttribute
    const road = roadWear(traffic, tier.tier), track = roadWear(relicTraffic, tier.tier)
    roadTiles.forEach((index, i) => {
      const wear = regrowRoads ? roadWear(foundingRoadTraffic(map, index, map.tiles[index] === "track" ? relicTraffic : traffic), tier.tier)
        : map.tiles[index] === "track" ? track : road
      land.setY(i, wear.edge); land.setZ(i, wear.inner)
      land.setW(i, regrowRoads && !tier.paved ? foundingRoadStrength(map, index) : 1)
      const [start, count] = segmentData.ranges.get(index) ?? [0, 0]
      surface.setZ(i, start); surface.setW(i, count)
    })
    land.needsUpdate = surface.needsUpdate = true
  }, [revision, roadGeometry, roadTiles, traffic, relicTraffic, tier, regrowRoads, segmentData, wearSnapshot])

  return (
    <StaticBlock>
      <ElevationEdges bounds={bounds} revision={revision} />
      <WaterMotion bounds={bounds} revision={revision} waterPalette={waterPalette} edgeGrain={treeGround!.grain} turbulenceField={shared.turbulence} />
      <instancedMesh
        frustumCulled
        ref={groundMeshRef}
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, geometryCount - roadCount]}
      >
        <primitive object={groundGeometry} attach="geometry" />
        <primitive object={groundMaterial} attach="material" />
      </instancedMesh>

      <instancedMesh
        name="terrain-path"
        ref={roadMeshRef}
        key={tier.id}
        // Skip empty road batches, such as paths entirely covered by bridges.
        visible={roadCount > 0}
        frustumCulled
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, roadCount]}
      >
        <primitive object={roadGeometry} attach="geometry" />
        <primitive object={roadMaterial} attach="material" />
      </instancedMesh>

      {/*
        The road's edge line alone (see ROAD_EDGE_LAYER). It shares the road
        geometry, so the ragged line lands exactly where the visible one does;
        the terrain's ID copy below joins this pass to supply the depth, so a
        hill hides the verge behind it just as it does on screen.
      */}
      <instancedMesh
        key={`edge-${tier.id}`}
        visible={roadCount > 0}
        frustumCulled
        name="terrain-path-edge"
        ref={edgeMeshRef}
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, roadCount]}
        layers-mask={ROAD_EDGE_LAYER_MASK}
      >
        <primitive object={roadGeometry} attach="geometry" />
        <primitive object={edgeMaterial} attach="material" />
      </instancedMesh>

      {/*
        Terrain in the outline pass: ID 0 (black), depth only. It takes no
        outline itself, but its depth stops hidden object seams — say two
        buildings overlapping *behind* a hill — from drawing lines through it.
      */}
      <instancedMesh
        frustumCulled
        ref={idMeshRef}
        args={[undefined as unknown as THREE.BufferGeometry, undefined as unknown as THREE.Material, geometryCount]}
        layers-mask={OUTLINE_ID_LAYER_MASK | ROAD_EDGE_LAYER_MASK}
      >
        <primitive object={idGeometry} attach="geometry" />
        <primitive object={idMaterial} attach="material" />
      </instancedMesh>
    </StaticBlock>
  )
})
