import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { pathToFileURL } from "node:url"

const botEmail = "41898282+github-actions[bot]@users.noreply.github.com"
const botSubject = "chore(release): publish "
const generatedFiles = ["lib/releases.json", "package.json", "package-lock.json", "CHANGELOG.md"]

function git(cwd, ...args) {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim()
}

function readJson(cwd, name) {
  return JSON.parse(readFileSync(`${cwd}/${name}`, "utf8"))
}

function writeJson(cwd, name, value) {
  writeFileSync(`${cwd}/${name}`, `${JSON.stringify(value, null, 2)}\n`)
}

// Commit titles are data, never shell commands or executable Markdown.
function markdown(text) {
  return text.replace(/[\\`*_{}\[\]()<>#!|]/g, "\\$&")
}

export function renderChangelog(releases) {
  return "# Changelog\n\nGenerated by the release workflow. See [release rules](docs/releases.md).\n\n" +
    releases.map(({ version, title, summary, commit }) =>
      `## ${version} — ${markdown(title)}\n\n${markdown(summary)}\n` +
      (commit ? `\nSource commit: ${commit}\n` : "")
    ).join("\n")
}

export function generateRelease(cwd) {
  const history = readJson(cwd, "lib/releases.json")
  const head = git(cwd, "rev-parse", "HEAD")
  const firstParent = git(cwd, "rev-list", "--first-parent", "HEAD").split("\n")
  if (!firstParent.includes(history.lastProcessedCommit)) {
    throw new Error("Release cursor is not on main's first-parent history; refusing to renumber releases.")
  }
  const commits = git(cwd, "rev-list", "--first-parent", "--reverse", `${history.lastProcessedCommit}..HEAD`)
    .split("\n").filter(Boolean)
  const reviews = []
  let added = 0
  for (const commit of commits) {
    const subject = git(cwd, "show", "-s", "--format=%s", commit)
    const email = git(cwd, "show", "-s", "--format=%ae", commit)
    if (email === botEmail && subject.startsWith(botSubject)) continue

    const versionParts = history.releases[0].version.match(/^(\d+)\.(\d+)\.(\d+)$/)
    if (!versionParts) throw new Error("Expected a numeric major.minor.patch version")
    const version = `${versionParts[1]}.${versionParts[2]}.${Number(versionParts[3]) + 1}`
    // GitHub's merge commit includes the PR title after its first line.
    const body = git(cwd, "show", "-s", "--format=%b", commit)
    const summary = /^Merge pull request #\d+/.test(subject)
      ? `${body.split("\n").find(line => line.trim()) || subject} (${subject.match(/#\d+/)[0]})`
      : subject
    history.releases.unshift({ version, title: `Release ${version}`, summary, commit })
    history.releaseCount += 1
    added += 1

    if (history.releaseCount % 10 === 0) {
      const name = `docs/release-reviews/${String(history.releaseCount).padStart(4, "0")}.md`
      if (existsSync(`${cwd}/${name}`)) throw new Error(`Review checkpoint already exists: ${name}`)
      mkdirSync(`${cwd}/docs/release-reviews`, { recursive: true })
      const entries = history.releases.slice(0, 10).reverse()
      writeFileSync(`${cwd}/${name}`, `# Documentation review through ${version}\n\n` +
        "One workspace owns this review. Check for an existing review PR before starting.\n" +
        "Update descriptions once for this batch; distinguish implemented features from plans.\n\n" +
        "- [ ] Review the ten releases below against the current code.\n" +
        "- [ ] Update the game doc (`app/docs/page.tsx` and its components) where needed.\n" +
        "- [ ] Update GitHub documentation (`README.md` and relevant `docs/` pages) where needed.\n" +
        "- [ ] Check game-doc header/footer revision and date together if the design changed.\n" +
        "- [ ] Record the review PR and any sections checked that needed no changes.\n\n" +
        entries.map(entry => `- ${entry.version}: ${markdown(entry.summary)} (${entry.commit})`).join("\n") + "\n")
      reviews.push(name)
    }
  }
  if (!added) return []

  history.lastProcessedCommit = head
  writeJson(cwd, "lib/releases.json", history)
  const version = history.releases[0].version
  const pkg = readJson(cwd, "package.json")
  const lock = readJson(cwd, "package-lock.json")
  pkg.version = lock.version = lock.packages[""].version = version
  writeJson(cwd, "package.json", pkg)
  writeJson(cwd, "package-lock.json", lock)
  writeFileSync(`${cwd}/CHANGELOG.md`, renderChangelog(history.releases))
  return [...generatedFiles, ...reviews]
}

export function publish(cwd) {
  // Reset is restricted to the disposable Actions checkout, never a workspace.
  if (process.env.GITHUB_ACTIONS !== "true" || process.env.GITHUB_REF !== "refs/heads/main") {
    throw new Error("Publishing must run in GitHub Actions on main")
  }
  git(cwd, "config", "user.name", "github-actions[bot]")
  git(cwd, "config", "user.email", botEmail)
  for (let attempt = 0; attempt < 5; attempt += 1) {
    git(cwd, "fetch", "origin", "main")
    git(cwd, "reset", "--hard", "origin/main")
    // Remove only untracked checkpoints left by a rejected push attempt.
    git(cwd, "clean", "-fd", "--", "docs/release-reviews/")
    const files = generateRelease(cwd)
    if (!files.length) return
    git(cwd, "add", "--", ...files)
    const version = readJson(cwd, "lib/releases.json").releases[0].version
    git(cwd, "commit", "-m", `${botSubject}${version}`)
    try {
      git(cwd, "push", "origin", "HEAD:main")
      return
    } catch (error) {
      // A concurrent merge wins. Recompute from its current state; never force push.
      if (attempt === 4) throw error
    }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv[2] !== "--publish") throw new Error("Use --publish inside GitHub Actions")
  publish(process.cwd())
}
